#!/bin/bash
echo "Updating mirror and system"
sudo pacman-mirrors --country Canada
#sudo pacman-mirrors -f 0           # remove this - it is overlapping line above
sudo pacman -Syyu --noconfirm       # execute this before installing yay
sudo pacman -S yay pamac --noconfirm
# yay -Syyua --noconfirm            # remove this - it overlaps the pacman sync command

###############################
echo "Install coding packages"
coding_pkgs="base-devel gcc-fortran r rstudio-desktop-bin visual-studio-code-bin"
yay -S $coding_pkgs --noconfirm

#miniconda part
yay -S miniconda3 --noconfirm
echo "[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc
sudo ln -s /opt/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
source ~/.bashrc
# deactivate conda by default
# conda config --set auto_activate_base false
###############################
echo "installing internet packages"
internet_pkgs="filezilla google-chrome"
yay -S $internet_pkgs --noconfirm
################################
echo "Install GIS packages"
GIS_pkgs="arrow podofo mariadb libjxl udunits python-owslib python-jinja-time python-psycopg2 python-gdal python-numpy python-pygments qgis grass saga-gis"
yay -S $GIS_pkgs --noconfirm
###############################
echo "Install productivity packages"
prdct_pkgs="flameshot notepadqq zoom slack-desktop inkscape meld libreoffice-fresh"
yay -S $prdct_pkgs --noconfirm
###############################
echo "Install utility packages"
utl_pkgs="gnome-disk-utility"
yay -S $utl_pkgs --noconfirm
###############################
#echo "mount hard drive to /media/hdd using gnome-disk-utility"
#echo "disk - select hard disk - settings - edit mount options - mount point - media/hdd"

#sudo mkdir -p /media/hdd
#sudo chmod -R 777 /media/hdd
#echo "mount hard drive to /media/hdd using gnome-disk-utility"
#echo "disk - select hard disk - settings - edit mount options - mount point - media/hdd"
###############################
#echo "System Settings - Appearance - Breeze Dark"
#echo "System Seetings - Startup and Shutdown - Desktop Session - Uncheck Confirm logout and offer shutdown options"

#echo "Backup system using timeshift"

#yay -S google-chrome --noconfirm
#yay -Sy base-devel --noconfirm
#yay -S linux61 linux61-headers --noconfirm

#echo "Add/Remove Software - Settings - ThirdParty - Enable AUR support - Check for updates"
